update to preserve default 'executionplans', 'eventpublishers' and 'eventstreams', to make this work, in image it should contain the above directories in /home/wso2carbon/wso2-tmp.

diff --git a/apim-320-fully-distributed-oke/templates/am/tm/apim-320-dist-oke-am-tm-statefulset.yaml b/apim-320-fully-distributed-oke/templates/am/tm/apim-320-dist-oke-am-tm-statefulset.yaml
--- a/apim-320-fully-distributed-oke/templates/am/tm/apim-320-dist-oke-am-tm-statefulset.yaml
+++ b/apim-320-fully-distributed-oke/templates/am/tm/apim-320-dist-oke-am-tm-statefulset.yaml
@@ -48,7 +48,7 @@ spec:
             - name: mysql-connector-jar
               mountPath: /mysql-connector-jar
         {{- end }}
-        - name: init-km
+        - name: init-tm
           image: busybox:1.32
           command: ['sh', '-c', 'echo -e "Checking for the availability of Key Manager deployment"; while ! nc -z {{ template "apim-320-dist-oke.resource.prefix" . }}-km-service 9443; do sleep 1; printf "-"; done; echo -e "  >> Key Manager has started";']
         - name: init-permissions-logs
@@ -77,8 +77,36 @@ spec:
                     fi;"
           ]
           volumeMounts:
-            - name: wso2am-tm-shared-storage-volume
+            - name: wso2am-tm-shared-executionplans-storage-volume
               mountPath: /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/executionplans
+        - name: init-permissions-eventpublishers
+          image: busybox
+          #          command: [ "sh", "-c", "find /home/wso2carbon/wso2am-3.2.1/repository/logs -not -path '/home/wso2carbon/wso2am-3.2.1/repository/logs/.snapshot*' -exec chmod 777 {} +" ]
+          command: [ "sh", "-c", "echo 'Setting permissions on /home/wso2carbon/wso2am-3.2.1/repository/deployment/sever/eventpublishers...';
+                find /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventpublishers -not -path '/home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventpublishers/.snapshot*' -exec chmod 777 {} +;
+                if [ $? -eq 0 ]; then
+                  echo 'Permissions set successfully.';
+                else
+                  echo 'Error setting permissions, please check the NFS server settings.';
+                fi;"
+          ]
+          volumeMounts:
+            - name: wso2am-tm-shared-eventpublishers-storage-volume
+              mountPath: /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventpublishers
+        - name: init-permissions-eventstreams
+          image: busybox
+          #          command: [ "sh", "-c", "find /home/wso2carbon/wso2am-3.2.1/repository/logs -not -path '/home/wso2carbon/wso2am-3.2.1/repository/logs/.snapshot*' -exec chmod 777 {} +" ]
+          command: [ "sh", "-c", "echo 'Setting permissions on /home/wso2carbon/wso2am-3.2.1/repository/deployment/sever/eventstreams...';
+            find /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventstreams -not -path '/home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventstreams/.snapshot*' -exec chmod 777 {} +;
+            if [ $? -eq 0 ]; then
+              echo 'Permissions set successfully.';
+            else
+              echo 'Error setting permissions, please check the NFS server settings.';
+            fi;"
+          ]
+          volumeMounts:
+            - name: wso2am-tm-shared-eventstreams-storage-volume
+              mountPath: /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventstreams
       containers:
         - name: wso2am-tm
 #          {{- if .Values.wso2.deployment.am.dockerRegistry }}
@@ -140,8 +168,12 @@ spec:
             - containerPort: 9443
               protocol: TCP
           volumeMounts:
-            - name: wso2am-tm-shared-storage-volume
+            - name: wso2am-tm-shared-executionplans-storage-volume
               mountPath: /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/executionplans
+            - name: wso2am-tm-shared-eventpublishers-storage-volume
+              mountPath: /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventpublishers
+            - name: wso2am-tm-shared-eventstreams-storage-volume
+              mountPath: /home/wso2carbon/wso2am-3.2.1/repository/deployment/server/eventstreams
             - name: wso2am-tm-log-storage-volume
               mountPath: /home/wso2carbon/wso2am-3.2.1/repository/logs
             - name: wso2am-tm-conf
@@ -159,9 +191,15 @@ spec:
         - name: {{ .Values.wso2.deployment.am.imagePullSecrets.secretName }}
       {{ end }}
       volumes:
-        - name: wso2am-tm-shared-storage-volume
+        - name: wso2am-tm-shared-executionplans-storage-volume
           persistentVolumeClaim:
             claimName: {{ template "apim-320-dist-oke.resource.prefix" . }}-am-tm-shared-executionplans-volume-claim
+        - name: wso2am-tm-shared-eventpublishers-storage-volume
+          persistentVolumeClaim:
+            claimName: { { template "apim-320-dist-oke.resource.prefix" . } }-am-tm-shared-eventpublishers-volume-claim
+        - name: wso2am-tm-shared-eventstreams-storage-volume
+          persistentVolumeClaim:
+            claimName: { { template "apim-320-dist-oke.resource.prefix" . } }-am-tm-shared-eventstreams-volume-claim
         - name: wso2am-tm-log-storage-volume
           persistentVolumeClaim:
             claimName: {{ template "apim-320-dist-oke.resource.prefix" . }}-am-tm-log-storage-volume-claim
